#MySql 셋팅
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_login_db
    username: root
    password: 1111
  sql:
    init:
      mode: never
# always: 매번, embedded: 내장 Db만 never: 모든 동작 안함
  jpa:
    defer-datasource-initialization: ture
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: validate